{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0d25942c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# # **Loading Hive Tables and Data Preparation for Analysis**\n",
    "\n",
    "import pyspark.sql.functions as F\n",
    "from pyspark.sql.window import Window\n",
    "from pyspark.sql.types import *\n",
    "from pyspark.sql.functions import * \n",
    "from pyspark.sql import SparkSession\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b3ac81ab",
   "metadata": {},
   "outputs": [],
   "source": [
    "spark = SparkSession.builder.appName(\"Market Analysis\").config(\n",
    "    \"spark.ui.port\", \"0\").config(\n",
    "        \"spark.sql.catalogImplementation=hive\").config(\n",
    "        \"spark.sql.warehouse.dir\",\n",
    "        \"hdfs://nameservice1/user/itv003722/warehouse\").config(\n",
    "            \"spark.serializer\",\n",
    "    \"org.apache.spark.serializer.KryoSerializer\").enableHiveSupport().getOrCreate()\n",
    "spark.sparkContext.setLogLevel('OFF')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "78afceb5",
   "metadata": {},
   "outputs": [],
   "source": [
    "MA = spark.table('bank_domain.market_analysis')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "eba4be3b",
   "metadata": {},
   "outputs": [],
   "source": [
    "MA.createOrReplaceTempView('MA')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3307a14d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+---+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+---+\n",
      "|age|         job| marital|education|default|balance|housing|loan|contact|day|month|duration|campaign|pdays|previous|poutcome|  y|\n",
      "+---+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+---+\n",
      "| 58|  management| married| tertiary|     no| 2143.0|    yes|  no|unknown|  5|  may|     261|       1|   -1|       0| unknown| no|\n",
      "| 44|  technician|  single|secondary|     no|   29.0|    yes|  no|unknown|  5|  may|     151|       1|   -1|       0| unknown| no|\n",
      "| 33|entrepreneur| married|secondary|     no|    2.0|    yes| yes|unknown|  5|  may|      76|       1|   -1|       0| unknown| no|\n",
      "| 47| blue-collar| married|  unknown|     no| 1506.0|    yes|  no|unknown|  5|  may|      92|       1|   -1|       0| unknown| no|\n",
      "| 33|     unknown|  single|  unknown|     no|    1.0|     no|  no|unknown|  5|  may|     198|       1|   -1|       0| unknown| no|\n",
      "| 35|  management| married| tertiary|     no|  231.0|    yes|  no|unknown|  5|  may|     139|       1|   -1|       0| unknown| no|\n",
      "| 28|  management|  single| tertiary|     no|  447.0|    yes| yes|unknown|  5|  may|     217|       1|   -1|       0| unknown| no|\n",
      "| 42|entrepreneur|divorced| tertiary|    yes|    2.0|    yes|  no|unknown|  5|  may|     380|       1|   -1|       0| unknown| no|\n",
      "| 58|     retired| married|  primary|     no|  121.0|    yes|  no|unknown|  5|  may|      50|       1|   -1|       0| unknown| no|\n",
      "| 43|  technician|  single|secondary|     no|  593.0|    yes|  no|unknown|  5|  may|      55|       1|   -1|       0| unknown| no|\n",
      "| 41|      admin.|divorced|secondary|     no|  270.0|    yes|  no|unknown|  5|  may|     222|       1|   -1|       0| unknown| no|\n",
      "| 29|      admin.|  single|secondary|     no|  390.0|    yes|  no|unknown|  5|  may|     137|       1|   -1|       0| unknown| no|\n",
      "| 53|  technician| married|secondary|     no|    6.0|    yes|  no|unknown|  5|  may|     517|       1|   -1|       0| unknown| no|\n",
      "| 58|  technician| married|  unknown|     no|   71.0|    yes|  no|unknown|  5|  may|      71|       1|   -1|       0| unknown| no|\n",
      "| 57|    services| married|secondary|     no|  162.0|    yes|  no|unknown|  5|  may|     174|       1|   -1|       0| unknown| no|\n",
      "| 51|     retired| married|  primary|     no|  229.0|    yes|  no|unknown|  5|  may|     353|       1|   -1|       0| unknown| no|\n",
      "| 45|      admin.|  single|  unknown|     no|   13.0|    yes|  no|unknown|  5|  may|      98|       1|   -1|       0| unknown| no|\n",
      "| 57| blue-collar| married|  primary|     no|   52.0|    yes|  no|unknown|  5|  may|      38|       1|   -1|       0| unknown| no|\n",
      "| 60|     retired| married|  primary|     no|   60.0|    yes|  no|unknown|  5|  may|     219|       1|   -1|       0| unknown| no|\n",
      "| 33|    services| married|secondary|     no|    0.0|    yes|  no|unknown|  5|  may|      54|       1|   -1|       0| unknown| no|\n",
      "+---+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+---+\n",
      "only showing top 20 rows\n",
      "\n"
     ]
    }
   ],
   "source": [
    "MA.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "37e9c936",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "root\n",
      " |-- age: integer (nullable = true)\n",
      " |-- job: string (nullable = true)\n",
      " |-- marital: string (nullable = true)\n",
      " |-- education: string (nullable = true)\n",
      " |-- default: string (nullable = true)\n",
      " |-- balance: double (nullable = true)\n",
      " |-- housing: string (nullable = true)\n",
      " |-- loan: string (nullable = true)\n",
      " |-- contact: string (nullable = true)\n",
      " |-- day: string (nullable = true)\n",
      " |-- month: string (nullable = true)\n",
      " |-- duration: long (nullable = true)\n",
      " |-- campaign: integer (nullable = true)\n",
      " |-- pdays: integer (nullable = true)\n",
      " |-- previous: integer (nullable = true)\n",
      " |-- poutcome: string (nullable = true)\n",
      " |-- y: string (nullable = true)\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "45211"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "MA.printSchema()\n",
    "MA.count()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "42a9434d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+----------+-----+---------------+\n",
      "|subscribed|total|success_percent|\n",
      "+----------+-----+---------------+\n",
      "|      5289|45211|           11.7|\n",
      "+----------+-----+---------------+\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#Marketing Success Rate (No. of people subscribed / total no. of entries)\n",
    "spark.sql(\"\"\"\n",
    " select a.subscribed,B.total, round((a.subscribed/b.total)*100,2) as success_percent from (select count(*)\n",
    "as subscribed from MA where y='yes') a,(select count(*) as total from MA) b\n",
    "         \"\"\").show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "bb4681e3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+---------------+\n",
      "|failure_percent|\n",
      "+---------------+\n",
      "|           88.3|\n",
      "+---------------+\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#Marketing Failure Rate\n",
    "Market_failure=spark.sql(\"\"\"\n",
    " select round((a.not_subscribed/b.total)*100,2) as failure_percent from (select\n",
    "count(*) as not_subscribed from MA where y='no') a,(select count(*) as total from MA) b\n",
    "         \"\"\").show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "ec157ec5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<table border='1'>\n",
       "<tr><th>max_age</th><th>min_age</th><th>average_age</th></tr>\n",
       "<tr><td>95</td><td>18</td><td>41.67</td></tr>\n",
       "</table>\n"
      ],
      "text/plain": [
       "+-------+-------+-----------+\n",
       "|max_age|min_age|average_age|\n",
       "+-------+-------+-----------+\n",
       "|     95|     18|      41.67|\n",
       "+-------+-------+-----------+"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "#MA.select(max(\"age\")).show()\n",
    "spark.sql(\n",
    "\"\"\"\n",
    "select max(age) as max_age,min(age) as min_age,round(avg(age),2) as average_age from MA where y='yes'\n",
    "\n",
    "\"\"\"\n",
    ")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "0cb952f6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+---+----------------+\n",
      "|age|count((y = yes))|\n",
      "+---+----------------+\n",
      "| 95|               2|\n",
      "| 94|               1|\n",
      "| 93|               2|\n",
      "| 92|               2|\n",
      "| 90|               2|\n",
      "| 89|               3|\n",
      "| 88|               2|\n",
      "| 87|               4|\n",
      "| 86|               9|\n",
      "| 85|               5|\n",
      "| 84|               9|\n",
      "| 83|              22|\n",
      "| 82|              19|\n",
      "| 81|              17|\n",
      "| 80|              31|\n",
      "| 79|              25|\n",
      "| 78|              30|\n",
      "| 77|              44|\n",
      "| 76|              32|\n",
      "| 75|              39|\n",
      "+---+----------------+\n",
      "only showing top 20 rows\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#Age wise subscription to deposit\n",
    "#agewise_status=spark.sql(\"\"\"\n",
    "#select age, count(*) as number from MA where y='yes' group by age order by age desc\n",
    "#\"\"\").show()\n",
    "\n",
    "\n",
    "MA.groupBy(\"age\").agg(count(col(\"y\")=='yes')).alias(\"aa\").orderBy(col(\"age\").desc()).show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "9a2d0554",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+--------+\n",
      "| marital|\n",
      "+--------+\n",
      "|divorced|\n",
      "| married|\n",
      "|  single|\n",
      "+--------+\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#Distinct marital Status\n",
    "MA.select(\"marital\").distinct().show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e95992fb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6f2a4fc1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>marital</th>\n",
       "      <th>y</th>\n",
       "      <th>count((y = yes))</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>divorced</td>\n",
       "      <td>yes</td>\n",
       "      <td>622</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>single</td>\n",
       "      <td>no</td>\n",
       "      <td>10878</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>single</td>\n",
       "      <td>yes</td>\n",
       "      <td>1912</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>divorced</td>\n",
       "      <td>no</td>\n",
       "      <td>4585</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>married</td>\n",
       "      <td>yes</td>\n",
       "      <td>2755</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    marital    y  count((y = yes))\n",
       "0  divorced  yes               622\n",
       "1    single   no             10878\n",
       "2    single  yes              1912\n",
       "3  divorced   no              4585\n",
       "4   married  yes              2755"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Marital Category wise analysis\n",
    "pandas_df = MA.select(\"marital\", \"y\").groupby(\"marital\", \"y\").agg(count(col(\"y\")==\"yes\")).alias(\"subscribed_count\").distinct().toPandas()\n",
    "\n",
    "pandas_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "5a409339",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYMAAAE3CAYAAABIPy1xAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAU2klEQVR4nO3df7DddX3n8edLEsgG0pBAxkXCzE0HJSILsSSRrdQfSIEutgSVam0tzlJpd2GX4u62LDNrmTLb2upqhdktkym2rGsrLf6AllErCMzUFcbwoyI/BMYKuQh6Gwg/sgQIee8f93vxck1yz03O9/y6z8fMnZzzPd8f7/M9mfP6fD7fHydVhSRpfntVvwuQJPWfYSBJMgwkSYaBJAnDQJKEYSBJwjCQBlqS7yc5ud91aPQZBhoJzZfmc0meTfJkkuuTHNHlbSxJ8olmW9uSPJLkmiRv6uZ2pH4wDDRKfrGqDgIOA34IXL43K0myYBfTDgC+Dvwr4J3ATwGvBz4H/EKn65EGlWGgkVNV24FrgKOnpiU5PcmdSZ5OsjnJJdNeG0tSSc5J8giTX/ozfQBYCWyoqu9U1UtVta2qrqmq6euqJOcleRB4sJn2qWabTye5PcnPTZv/kqZ3cXWSZ5LckeS4Gdtek+TbSZ5q5lu073tJeiXDQCMnyWLgvcCt0yZvA34dOBg4Hfh3STbMWPStTLb2T93Fak8GvlpV2zooYQPwJn4cRt8C1gDLgb8E/mbGF/oZwN9Me/1LSRZOe/2XgdOAVcCxwAc7qEGaE8NAo+RLSbYCTwE/D3xs6oWqurmq7q6qnVX1beCvmPzyn+6SprX/3C7WfSjw+NSTJGuSbG1a+9+dMe8fVtUTU+upqv9TVVuqakdV/Q/gAOCoafPf3vQwXgQ+ASwCTpj2+mVV9YOqegL4WyaDReoqw0CjZENVHczkl+n5wC1J/iVAkjcluSnJRJKngN9i8gt+us17WPcWJo9FAFBVdzXbeheTX+67XU+S/5zkvmaYZyuwdMa2X56/qnYC48Brpr3++LTH/w84aA91SnvFMNDIacbzvwC8BJzYTP5L4DrgiKpaClwBZOaie1jtjcApSQ7spISpB83xgd9hcqhnWRMgT83Y9hHT5n8Vk8cmftDBdqSuMQw0cjLpDGAZcF8zeQnwRFVtT7IeeP8cV/u/gceALyY5Jsl+zbj/2lmWWwLsACaABUk+wuSZSNMdn+RdzdlHvw08zyuPd0itMww0Sv42ybPA08B/B86uqnua1/498PtJngE+Avz1XFbcnKH0duBe4PpmG98F1jHZ6t+drwJfAR4AHga285PDUdcyecD7SSbPWnpXc/xA6pn44zZS/zSnuB5ZVb/W71o0v9kzkCQZBpIkh4kkSdgzkCQBQ3EjrUMPPbTGxsb6XYYkDZXbb7/9n6tqRSfzDkUYjI2NsWnTpn6XIUlDJcnDnc7rMJEkyTCQJBkGkiSG5JjBrrz44ouMj4+zffv2fpfSNYsWLWLlypUsXLhw9pklqYuGNgzGx8dZsmQJY2NjJDNvPjl8qootW7YwPj7OqlWr+l2OpHlmaIeJtm/fziGHHDISQQCQhEMOOWSkejqShsfQhgEwMkEwZdTej6ThMdRhIEnqjqE9ZjDT2EXXd3V93//o6V1dnyQNMnsGkiTDYF9s2LCB448/nje84Q1s3LgRgCuvvJLXve51rF+/ng996EOcf/75AExMTPDud7+bdevWsW7dOr7xjW/0s3RJeoWRGSbqh09/+tMsX76c5557jnXr1nH66adz6aWXcscdd7BkyRJOOukkjjvuOAAuuOACLrzwQk488UQeeeQRTj31VO67775ZtiBJvWEY7IPLLruML37xiwBs3ryZz3zmM7z1rW9l+fLlAJx11lk88MADANxwww3ce++9Ly/79NNP8+yzz3LQQQf1vnBJmsEw2Es333wzN9xwA9/85jdZvHgxb3vb21i9evVuW/s7d+7k1ltvZdGiRT2uVJJm5zGDvfTUU0+xbNkyFi9ezP3338+tt97Ktm3buOWWW3jyySfZsWMHn//851+e/5RTTuHyyy9/+fldd93Vh6oladdGpmfQ61NBTzvtNK644gpe//rXc9RRR3HCCSdw+OGHc/HFF7N+/XqWL1/O6tWrWbp0KTA5pHTeeedx7LHHsmPHDt7ylrdwxRVX9LRmSdqdkQmDXjvggAP48pe//BPT165dy7nnnsuOHTs488wz2bBhAwCHHnooV199dY+rlKTOOEzUZZdccglr1qzhmGOOYdWqVS+HgSQNMnsGXfbxj3+83yVI0pwNdc+gqvpdQleN2vuRNDyGNgwWLVrEli1bRuYLdOr3DDz1VFI/DO0w0cqVKxkfH2diYqLfpXTN1C+dSVKvDW0YLFy40F8Ek6QuGdphIklS9xgGkiTDQJJkGEiSMAwkSRgGkiQMA0kShoEkCcNAkoRhIEnCMJAkYRhIkjAMJEkYBpIkDANJEi2HQZILk9yT5DtJ/irJoiSrktyW5KEkVyfZv80aJEmzay0MkhwO/EdgbVUdA+wHvA/4I+CTVXUk8CRwTls1SJI60/Yw0QLgXyRZACwGHgNOAq5pXr8K2NByDZKkWbQWBlX1KPBx4BEmQ+Ap4HZga1XtaGYbBw7f1fJJzk2yKcmmUfqdY0kaRG0OEy0DzgBWAa8BDgRO63T5qtpYVWurau2KFStaqlKSBO0OE50M/FNVTVTVi8AXgDcDBzfDRgArgUdbrEGS1IE2w+AR4IQki5MEeAdwL3AT8J5mnrOBa1usQZLUgTaPGdzG5IHiO4C7m21tBH4X+HCSh4BDgCvbqkGS1JkFs8+y96rq94DfmzH5e8D6NrcrSZobr0CWJBkGkiTDQJKEYSBJwjCQJGEYSJIwDCRJGAaSJAwDSRKGgSQJw0CShGEgScIwkCRhGEiSMAwkSRgGkiQMA0kShoEkCcNAkoRhIEnCMJAkYRhIkjAMJEkYBpIkDANJEoaBJAnDQJKEYSBJQ2PsoutbW7dhIEkyDCRJhoEkCcNAkoRhIEnCMJAkYRhIkmg5DJIcnOSaJPcnuS/Jv06yPMnXkjzY/LuszRokSbNru2fwKeArVbUaOA64D7gIuLGqXgvc2DyXJPVRa2GQZCnwFuBKgKp6oaq2AmcAVzWzXQVsaKsGSVJn2uwZrAImgD9PcmeSP0tyIPDqqnqsmedx4NW7WjjJuUk2Jdk0MTHRYpnz2/TL27t5qXubl82rXX5281ObYbAA+BngT6vqjcA2ZgwJVVUBtauFq2pjVa2tqrUrVqxosUxJUpthMA6MV9VtzfNrmAyHHyY5DKD590ct1qBdsOXXHe5HjZLWwqCqHgc2JzmqmfQO4F7gOuDsZtrZwLVt1SBJ6kzbZxP9B+CzSb4NrAH+APgo8PNJHgRObp6rB2zJStqdBW2uvKruAtbu4qV3tLldSdLceAWyJMkw0Cvty1CSw1Dtcx+rLYaBJMkwUO95cdvczZf3OUjm2z43DCRJhoFGy3xrzWn+aPv/tmEgSRqdMLBFKKmXRu07Z2TCQJK09+YUBkkWt1WI2jWIrZhBrGk+8nMYDP3+HDoKgyQ/m+Re4P7m+XFJ/lerlUmSeqbTnsEngVOBLQBV9Y9M/oqZRkS/WyVzNbPe2Z4PsmGqVaOr42Giqto8Y9JLXa5FktQnnd61dHOSnwUqyULgAiZ/3F6SNAI67Rn8FnAecDjwKJO/TXBeSzWpyxyGkDSbjnoGVfXPwK+2XIskqU86PZvosl38XZrkjLYLHHS2ugfH7j4LP6P5pR+fd9vb7MV76nSYaBGTQ0MPNn/HAiuBc5L8SSuVSZJ6ptMwOBZ4e1VdXlWXM/nbxauBM4FT2ipOr2QLt/fc593l/hxcnYbBMuCgac8PBJZX1UvA812vSpLUU52GwR8DdyX58yR/AdwJfCzJgcANbRUn7cp8al0O23vdVb3D9h4GxdhF1/d033V6NtGVSb4MfIDJ6wv+Hhivqm3Af2mxPklSD3R6NtFvAF8FLgIuBK4ELmmvLEltGoXWei/fwyjsr9l0Okx0AbAOeLiq3g68EdjaVlGSpN7qNAy2V9V2gCQHVNX9wFHtlSVJ6qVO7000nuRg4EvA15I8CTzcVlGSpN7q9ADymc3DS5LcBCwFvtJaVZKknprzz15W1S1VdV1VvdBGQd3Uq4M+bW5nPhy42lv92jd+JoPJz2Xf+BvIkqThDYNRaQWMyvvoJ/fh/NPvz3xq+/2uo5uGNgwkSd1jGOyDUTgm0UvD9j4Gpd5BqWNQuX+6wzCQJBkGal+vW262FDVKevX/ufUwSLJfkjuT/F3zfFWS25I8lOTqJPu3XYMkac960TO4gMk7nU75I+CTVXUk8CRwTg9q0Ay2nrUn/v+Yf1oNgyQrgdOBP2ueBzgJuKaZ5SpgQ5s1SJJm13bP4E+A3wF2Ns8PAbZW1Y7m+ThweMs1SJJm0VoYJHkn8KOqun0vlz83yaYkmyYmJnY5Tydd2WHu7g5r7cNatzSftdkzeDPwS0m+D3yOyeGhTwEHJ5m6Qd5K4NFdLVxVG6tqbVWtXbFiRYtlSpJaC4Oq+q9VtbKqxoD3AV+vql8FbgLe08x2NnDtXNbbz1bnqF1kZgt+bvxlrb03au+n2wZh//TjOoPfBT6c5CEmjyFc2YcaJEnT9CQMqurmqnpn8/h7VbW+qo6sqrOq6vlub69bKbun9QxCkg+zUdl/o3jDsmHk/t93XoEsSTIMNLqGqbXY71r7vf29NUi992Hdh1MMA0nSaITBsCey2jNM/zeGqVa1p1//D0YiDCRJ+8YwkCQZBp3oRbdtkIYIBqkWSb1hGEiSRi8MbNX21+72v5/L4On3rV2m/obNMNbciZELA0nS3BkGHer1bQdGtfUxqu+rF/Z13+1q+ZnTuvn5DMpn3XYdg/I+95VhIEkazjDo99k9o9ISaNuo7Kc230c/9lEvj+sM+/+BYa9/LoYyDCRJ3WUYzKLTlkE3WhD97vFo99ocW+/Fenu1/l5vR91jGEiSRjcMhrVlMqx1zxednJHTrW2M4pk9veKPDs3dyIaBJKlzhoEkafjDYBS6gf1+D/3evkZLP29J0vbpsaN8AH7ow0CStO8MA0nqo7n2AtrqNRgGkiTDQO3yeIQ0HAwDSZJhMCxsYUtqk2EgSTIMJGlQ9HMEwDCQJBkGktSJUT9uZxhIkgwDSZJhIKnHRn24ZVgZBpKk0QoDWxyStHdaC4MkRyS5Kcm9Se5JckEzfXmSryV5sPl3WVs1SJI602bPYAfwn6rqaOAE4LwkRwMXATdW1WuBG5vnkqQ+ai0MquqxqrqjefwMcB9wOHAGcFUz21XAhrZqkCR1pifHDJKMAW8EbgNeXVWPNS89Drx6N8ucm2RTkk0TExO9KFOS5q3WwyDJQcDngd+uqqenv1ZVBdSulquqjVW1tqrWrlixou0yJWleazUMkixkMgg+W1VfaCb/MMlhzeuHAT9qswZJ0uzaPJsowJXAfVX1iWkvXQec3Tw+G7i2rRokSZ1Z0OK63wx8ALg7yV3NtIuBjwJ/neQc4GHgl1usQZLUgdbCoKr+AchuXn5HW9uVJM3dSF2BLEnaO4aBJMkwkCQZBpIkDANJEoaBJAnDQJKEYSBJwjCQJGEYSJIwDCRJGAaSJAwDSRKGgSQJw0CShGEgScIwkCRhGEiSMAwkSRgGkiQMA0kShoEkCcNAkoRhIEnCMJAkYRhIkjAMJEkYBpIkDANJEoaBJAnDQJKEYSBJwjCQJGEYSJIwDCRJ9CkMkpyW5LtJHkpyUT9qkCT9WM/DIMl+wP8EfgE4GviVJEf3ug5J0o/1o2ewHnioqr5XVS8AnwPO6EMdkqRGqqq3G0zeA5xWVb/RPP8A8KaqOn/GfOcC5zZPj+9pkZI0Iqoqncy3oO1C9lZVbQQ2AiTpbWJJ0jzTj2GiR4Ejpj1f2UyTJPVJP8LgW8Brk6xKsj/wPuC6PtQhSWr0fJioqnYkOR/4KrAf8Omqume2xdqvTJLmr54fQJYkDR6vQJYkGQaSJMNAkoRhIEliwC46S/LTwIP9rkOSRklV7TfbPAN1NlGSFxmwgJKkYdfJLSkGKgymePsJSeqeTsLAYwaSpIENA3sGktRDgxoGq4EX+l2EJI2AX+lkpoE8ZjAlyXZgYb/rkKQhtHXqQVUdMtvMAxUGHjiWpO4bxgPIvwk83/xJknpkoHoGU5I8CxzY7zokaRR4nYEkacoLVXXA7l4ctGGiKc/0uwBJGjH77+lFewaSNE/sabho4HoGBoEk9d7AhQHwHPBiv4uQpBHyUvO3W4M6TPQcsKjfdUjSKBjG6wym3NTvAiRpPhm4nkGS/YAd/a5DkkZFJz2Dgfshmap6KZm1bknSru1VC3/gwqDxEjDrz7RJkn5CAQtqjsM+AzdMBJ5eKkndNLQHkDspXJLUPQMVBkn+W5IXkrzAZFfHHoIk7b2Ov0cHapgoyfPMcv8MSdLcDPNdS3cCDhVJUhcM7TEDDAJJ6qlBDQNJUg8Nahjs7HcBkjSfDGoYPNHvAiRpRHTUuB7UMLiUWW63KknqSEff8wN5NhF4FbIkdcswn00kSeqOjhrWA3mjuiSb+12DJA25OZ2IM6g9gz/tdwGSNOReNe1vVgPVM0jyYeBj/a5DkobYzB7B450sNFBhAPwSg9tbkaRhMPM79LC9Wajfnsa7lUpSN3V0e59BC4OD+l2AJM1HA3mdQZKtwNJ+1yFJo2CYrzNY3O8CJGk+GdQwuBmPG0hSN7zQyUwDOUwEkOT9wFXAfv2uRZKG1N9X1WmdzDiwYSBJ6p1BHSaSJPWQYSBJMgykbkjymiTXNI/XJPk3HSzztiR/13510uwMA2kfJVlQVT+oqvc0k9YAs4aBNEgMA81bScaS3J/kL5I8kOSzSU5O8o0kDyZZ3/x9M8mdSf5vkqOaZT+Y5LokXwdubNb1nST7A78PvDfJXUneu7t1SINk0G5UJ/XakcBZwL8FvgW8HziRyZsmXgz8OvBzVbUjycnAHwDvbpb9GeDYqnoiyRhAVb2Q5CPA2qo6HyDJT+1hHdJAMAw03/1TVd0NkOQe4MaqqiR3A2NM3hblqiSvZfJCyIXTlv1aVT3RwTb2tA5pIDhMpPnu+WmPd057vpPJxtKlwE1VdQzwi8CiafNv63Abe1qHNBAMA2nPlgKPNo8/2OEyzwBL9nEdUk8ZBtKe/THwh0nupPNh1ZuAo6cOIO/lOqSe8nYUkiR7BpIkw0CShGEgScIwkCRhGEiSMAwkSRgGkiTg/wM8255siQNlnAAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "#Visualization of impact of marital status  \n",
    "# bar graph using Pandas\n",
    "pandas_df.plot(x=\"marital\", y=\"age\", kind=\"bar\")\n",
    "plt.xlabel(\"marital\")\n",
    "plt.ylabel(\"age\")\n",
    "plt.title(\"Bar Graph\")\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "c63a81fa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'Median': 732.0, 'Average': 1804.2679145396105}\n"
     ]
    }
   ],
   "source": [
    "#quality of customers by checking average balance, median balance of customers\n",
    "# spark.sql(\"\"\"\n",
    "# select  round(avg(balance)) as Average_balance,median(balance) as median_balance from MA where y='yes'\n",
    "# \"\"\").show()\n",
    "\n",
    "\n",
    "#Average=MA.select(\"balance\").agg(mean(\"balance\")).show()\n",
    "quantiles = MA.filter(col(\"y\")=='yes').approxQuantile('balance', [0.5], 0.001)\n",
    "median = quantiles[0]\n",
    "\n",
    "average = MA.filter(col(\"y\")=='yes').agg({\"balance\": \"mean\"}).collect()[0][0]\n",
    "\n",
    "# # Show the median and Average\n",
    "print({\"Median\": median,\"Average\":average})\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "316ab847",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Age wise subscription to deposit\n",
    "agewise_status=spark.sql(\"\"\"\n",
    "select age, count(*) as number from MA where y='yes' group by age order by age desc\n",
    "\"\"\").show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "e88d21f6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+--------+------+\n",
      "| marital|number|\n",
      "+--------+------+\n",
      "|divorced|   622|\n",
      "| married|  2755|\n",
      "|  single|  1912|\n",
      "+--------+------+\n",
      "\n",
      "-------------------------------------------\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>marital</th>\n",
       "      <th>sum_value</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>divorced</td>\n",
       "      <td>622</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>married</td>\n",
       "      <td>2755</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>single</td>\n",
       "      <td>1912</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    marital  sum_value\n",
       "0  divorced        622\n",
       "1   married       2755\n",
       "2    single       1912"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#marital status wise subscription to deposit\n",
    "# MA.groupBy(\"marital\").agg(count(col(\"y\")==\"yes\")).orderBy(col(\"marital\").desc()).toPandas().head()\n",
    "Marital_status=spark.sql(\"\"\"\n",
    "select marital, count(*) as number from MA where y='yes' group by marital\n",
    "\"\"\").show()\n",
    "print(\"-------------------------------------------\")\n",
    "result = MA.groupBy(\"marital\").agg(count(when(col(\"y\") =='yes', col(\"y\"))).alias(\"sum_value\"))\n",
    "#MA.groupBy('marital').agg(count(when( MA.y='yes',MA.y)).alias(\"sum_value\"))\n",
    "\n",
    "result.toPandas().head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "693bca30",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+---+--------+------+\n",
      "|age| marital|number|\n",
      "+---+--------+------+\n",
      "| 18|  single|     7|\n",
      "| 19|  single|    11|\n",
      "| 20|  single|    14|\n",
      "| 20| married|     1|\n",
      "| 21|  single|    21|\n",
      "| 21| married|     1|\n",
      "| 22|  single|    40|\n",
      "| 23| married|     2|\n",
      "| 23|  single|    42|\n",
      "| 24|  single|    58|\n",
      "| 24| married|    10|\n",
      "| 25| married|    14|\n",
      "| 25|  single|    99|\n",
      "| 26|  single|   121|\n",
      "| 26| married|    13|\n",
      "| 27|divorced|     2|\n",
      "| 27| married|    29|\n",
      "| 27|  single|   110|\n",
      "| 28| married|    20|\n",
      "| 28|  single|   138|\n",
      "+---+--------+------+\n",
      "only showing top 20 rows\n",
      "\n",
      "----------------------------------------------\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>marital</th>\n",
       "      <th>age</th>\n",
       "      <th>y</th>\n",
       "      <th>count((marital = married))</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>single</td>\n",
       "      <td>51</td>\n",
       "      <td>yes</td>\n",
       "      <td>8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>married</td>\n",
       "      <td>72</td>\n",
       "      <td>yes</td>\n",
       "      <td>23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>married</td>\n",
       "      <td>80</td>\n",
       "      <td>no</td>\n",
       "      <td>18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>married</td>\n",
       "      <td>88</td>\n",
       "      <td>no</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>married</td>\n",
       "      <td>81</td>\n",
       "      <td>no</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>divorced</td>\n",
       "      <td>80</td>\n",
       "      <td>no</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>married</td>\n",
       "      <td>30</td>\n",
       "      <td>no</td>\n",
       "      <td>616</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>single</td>\n",
       "      <td>49</td>\n",
       "      <td>no</td>\n",
       "      <td>87</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>single</td>\n",
       "      <td>19</td>\n",
       "      <td>yes</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>divorced</td>\n",
       "      <td>38</td>\n",
       "      <td>no</td>\n",
       "      <td>147</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    marital  age    y  count((marital = married))\n",
       "0    single   51  yes                           8\n",
       "1   married   72  yes                          23\n",
       "2   married   80   no                          18\n",
       "3   married   88   no                           2\n",
       "4   married   81   no                           5\n",
       "5  divorced   80   no                           1\n",
       "6   married   30   no                         616\n",
       "7    single   49   no                          87\n",
       "8    single   19  yes                          11\n",
       "9  divorced   38   no                         147"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#age and marital status together mattered for a subscription to deposit scheme\n",
    "status=spark.sql(\"\"\"\n",
    "select age,marital, count(*) as number from MA where y='yes' group by age, marital order by age \n",
    "\"\"\").show()\n",
    "print(\"----------------------------------------------\")\n",
    "MA.select(\"marital\",\"age\",\"y\").groupBy(\"marital\",\"age\",\"y\").agg(count(col(\"marital\")==\"married\")).alias(\"a\").toPandas().head(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "df90994d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "9db0cf2c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "c24e37f0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>age</th>\n",
       "      <th>job</th>\n",
       "      <th>marital</th>\n",
       "      <th>education</th>\n",
       "      <th>default</th>\n",
       "      <th>balance</th>\n",
       "      <th>housing</th>\n",
       "      <th>loan</th>\n",
       "      <th>contact</th>\n",
       "      <th>day</th>\n",
       "      <th>month</th>\n",
       "      <th>duration</th>\n",
       "      <th>campaign</th>\n",
       "      <th>pdays</th>\n",
       "      <th>previous</th>\n",
       "      <th>poutcome</th>\n",
       "      <th>y</th>\n",
       "      <th>Age_Category</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>58</td>\n",
       "      <td>management</td>\n",
       "      <td>married</td>\n",
       "      <td>tertiary</td>\n",
       "      <td>no</td>\n",
       "      <td>2143.0</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>unknown</td>\n",
       "      <td>5</td>\n",
       "      <td>may</td>\n",
       "      <td>261</td>\n",
       "      <td>1</td>\n",
       "      <td>-1</td>\n",
       "      <td>0</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>old</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>44</td>\n",
       "      <td>technician</td>\n",
       "      <td>single</td>\n",
       "      <td>secondary</td>\n",
       "      <td>no</td>\n",
       "      <td>29.0</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>unknown</td>\n",
       "      <td>5</td>\n",
       "      <td>may</td>\n",
       "      <td>151</td>\n",
       "      <td>1</td>\n",
       "      <td>-1</td>\n",
       "      <td>0</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>Middle Age</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>33</td>\n",
       "      <td>entrepreneur</td>\n",
       "      <td>married</td>\n",
       "      <td>secondary</td>\n",
       "      <td>no</td>\n",
       "      <td>2.0</td>\n",
       "      <td>yes</td>\n",
       "      <td>yes</td>\n",
       "      <td>unknown</td>\n",
       "      <td>5</td>\n",
       "      <td>may</td>\n",
       "      <td>76</td>\n",
       "      <td>1</td>\n",
       "      <td>-1</td>\n",
       "      <td>0</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>Middle Age</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>47</td>\n",
       "      <td>blue-collar</td>\n",
       "      <td>married</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>1506.0</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>unknown</td>\n",
       "      <td>5</td>\n",
       "      <td>may</td>\n",
       "      <td>92</td>\n",
       "      <td>1</td>\n",
       "      <td>-1</td>\n",
       "      <td>0</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>Middle Age</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>33</td>\n",
       "      <td>unknown</td>\n",
       "      <td>single</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>1.0</td>\n",
       "      <td>no</td>\n",
       "      <td>no</td>\n",
       "      <td>unknown</td>\n",
       "      <td>5</td>\n",
       "      <td>may</td>\n",
       "      <td>198</td>\n",
       "      <td>1</td>\n",
       "      <td>-1</td>\n",
       "      <td>0</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>Middle Age</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>35</td>\n",
       "      <td>management</td>\n",
       "      <td>married</td>\n",
       "      <td>tertiary</td>\n",
       "      <td>no</td>\n",
       "      <td>231.0</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>unknown</td>\n",
       "      <td>5</td>\n",
       "      <td>may</td>\n",
       "      <td>139</td>\n",
       "      <td>1</td>\n",
       "      <td>-1</td>\n",
       "      <td>0</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>Middle Age</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>28</td>\n",
       "      <td>management</td>\n",
       "      <td>single</td>\n",
       "      <td>tertiary</td>\n",
       "      <td>no</td>\n",
       "      <td>447.0</td>\n",
       "      <td>yes</td>\n",
       "      <td>yes</td>\n",
       "      <td>unknown</td>\n",
       "      <td>5</td>\n",
       "      <td>may</td>\n",
       "      <td>217</td>\n",
       "      <td>1</td>\n",
       "      <td>-1</td>\n",
       "      <td>0</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>Young</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>42</td>\n",
       "      <td>entrepreneur</td>\n",
       "      <td>divorced</td>\n",
       "      <td>tertiary</td>\n",
       "      <td>yes</td>\n",
       "      <td>2.0</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>unknown</td>\n",
       "      <td>5</td>\n",
       "      <td>may</td>\n",
       "      <td>380</td>\n",
       "      <td>1</td>\n",
       "      <td>-1</td>\n",
       "      <td>0</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>Middle Age</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>58</td>\n",
       "      <td>retired</td>\n",
       "      <td>married</td>\n",
       "      <td>primary</td>\n",
       "      <td>no</td>\n",
       "      <td>121.0</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>unknown</td>\n",
       "      <td>5</td>\n",
       "      <td>may</td>\n",
       "      <td>50</td>\n",
       "      <td>1</td>\n",
       "      <td>-1</td>\n",
       "      <td>0</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>old</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>43</td>\n",
       "      <td>technician</td>\n",
       "      <td>single</td>\n",
       "      <td>secondary</td>\n",
       "      <td>no</td>\n",
       "      <td>593.0</td>\n",
       "      <td>yes</td>\n",
       "      <td>no</td>\n",
       "      <td>unknown</td>\n",
       "      <td>5</td>\n",
       "      <td>may</td>\n",
       "      <td>55</td>\n",
       "      <td>1</td>\n",
       "      <td>-1</td>\n",
       "      <td>0</td>\n",
       "      <td>unknown</td>\n",
       "      <td>no</td>\n",
       "      <td>Middle Age</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   age           job   marital  education default  balance housing loan  \\\n",
       "0   58    management   married   tertiary      no   2143.0     yes   no   \n",
       "1   44    technician    single  secondary      no     29.0     yes   no   \n",
       "2   33  entrepreneur   married  secondary      no      2.0     yes  yes   \n",
       "3   47   blue-collar   married    unknown      no   1506.0     yes   no   \n",
       "4   33       unknown    single    unknown      no      1.0      no   no   \n",
       "5   35    management   married   tertiary      no    231.0     yes   no   \n",
       "6   28    management    single   tertiary      no    447.0     yes  yes   \n",
       "7   42  entrepreneur  divorced   tertiary     yes      2.0     yes   no   \n",
       "8   58       retired   married    primary      no    121.0     yes   no   \n",
       "9   43    technician    single  secondary      no    593.0     yes   no   \n",
       "\n",
       "   contact day month  duration  campaign  pdays  previous poutcome   y  \\\n",
       "0  unknown   5   may       261         1     -1         0  unknown  no   \n",
       "1  unknown   5   may       151         1     -1         0  unknown  no   \n",
       "2  unknown   5   may        76         1     -1         0  unknown  no   \n",
       "3  unknown   5   may        92         1     -1         0  unknown  no   \n",
       "4  unknown   5   may       198         1     -1         0  unknown  no   \n",
       "5  unknown   5   may       139         1     -1         0  unknown  no   \n",
       "6  unknown   5   may       217         1     -1         0  unknown  no   \n",
       "7  unknown   5   may       380         1     -1         0  unknown  no   \n",
       "8  unknown   5   may        50         1     -1         0  unknown  no   \n",
       "9  unknown   5   may        55         1     -1         0  unknown  no   \n",
       "\n",
       "  Age_Category  \n",
       "0          old  \n",
       "1   Middle Age  \n",
       "2   Middle Age  \n",
       "3   Middle Age  \n",
       "4   Middle Age  \n",
       "5   Middle Age  \n",
       "6        Young  \n",
       "7   Middle Age  \n",
       "8          old  \n",
       "9   Middle Age  "
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#feature engineering for the bank and find the right age effect on the campaign\n",
    "result = MA.withColumn(\n",
    "    \"Age_Category\",\n",
    "    when(col(\"age\") <=20, \"Teen\")\n",
    "    .when((col(\"age\") >20) &( col(\"age\") < 32) , \"Young\")\n",
    "    .when((col(\"age\") >=33) & (col(\"age\") <=55), \"Middle Age\")\n",
    "        .otherwise(\"old\")\n",
    ")\n",
    "result.toPandas().head(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "9a75d01a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+---+------------+\n",
      "|         job| marital|education|default|balance|housing|loan|contact|day|month|duration|campaign|pdays|previous|poutcome|  y|Age_Category|\n",
      "+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+---+------------+\n",
      "|  management| married| tertiary|     no| 2143.0|    yes|  no|unknown|  5|  may|     261|       1|   -1|       0| unknown| no|         Old|\n",
      "|  technician|  single|secondary|     no|   29.0|    yes|  no|unknown|  5|  may|     151|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "|entrepreneur| married|secondary|     no|    2.0|    yes| yes|unknown|  5|  may|      76|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "| blue-collar| married|  unknown|     no| 1506.0|    yes|  no|unknown|  5|  may|      92|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "|     unknown|  single|  unknown|     no|    1.0|     no|  no|unknown|  5|  may|     198|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "|  management| married| tertiary|     no|  231.0|    yes|  no|unknown|  5|  may|     139|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "|  management|  single| tertiary|     no|  447.0|    yes| yes|unknown|  5|  may|     217|       1|   -1|       0| unknown| no|       Young|\n",
      "|entrepreneur|divorced| tertiary|    yes|    2.0|    yes|  no|unknown|  5|  may|     380|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "|     retired| married|  primary|     no|  121.0|    yes|  no|unknown|  5|  may|      50|       1|   -1|       0| unknown| no|         Old|\n",
      "|  technician|  single|secondary|     no|  593.0|    yes|  no|unknown|  5|  may|      55|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "|      admin.|divorced|secondary|     no|  270.0|    yes|  no|unknown|  5|  may|     222|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "|      admin.|  single|secondary|     no|  390.0|    yes|  no|unknown|  5|  may|     137|       1|   -1|       0| unknown| no|       Young|\n",
      "|  technician| married|secondary|     no|    6.0|    yes|  no|unknown|  5|  may|     517|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "|  technician| married|  unknown|     no|   71.0|    yes|  no|unknown|  5|  may|      71|       1|   -1|       0| unknown| no|         Old|\n",
      "|    services| married|secondary|     no|  162.0|    yes|  no|unknown|  5|  may|     174|       1|   -1|       0| unknown| no|         Old|\n",
      "|     retired| married|  primary|     no|  229.0|    yes|  no|unknown|  5|  may|     353|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "|      admin.|  single|  unknown|     no|   13.0|    yes|  no|unknown|  5|  may|      98|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "| blue-collar| married|  primary|     no|   52.0|    yes|  no|unknown|  5|  may|      38|       1|   -1|       0| unknown| no|         Old|\n",
      "|     retired| married|  primary|     no|   60.0|    yes|  no|unknown|  5|  may|     219|       1|   -1|       0| unknown| no|         Old|\n",
      "|    services| married|secondary|     no|    0.0|    yes|  no|unknown|  5|  may|      54|       1|   -1|       0| unknown| no|  Middle Age|\n",
      "+------------+--------+---------+-------+-------+-------+----+-------+---+-----+--------+--------+-----+--------+--------+---+------------+\n",
      "only showing top 20 rows\n",
      "\n"
     ]
    }
   ],
   "source": [
    "result.drop(\"age\").show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "935ba75e",
   "metadata": {},
   "outputs": [],
   "source": [
    "result.select(\"Age_Category\",\"y\").groupBy(\"Age_Category\").agg(count(col(\"y\"))==\"yes\").show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2b48693d",
   "metadata": {},
   "outputs": [],
   "source": [
    "spark.sql(\n",
    "\"\"\"\n",
    "select  Age_Category from result where y=\"yes\" \n",
    "\n",
    "\"\"\"\n",
    ").show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "5022d226",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "84118c33",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Pyspark 3",
   "language": "python",
   "name": "pyspark3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
